name: Count CPP Files

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Count .cpp files
        id: count
        run: echo "::set-output name=count::$(find . -name '*.cpp' | wc -l)"

  update-badge:
    needs: count-files
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update badge
        run: python update_badge.py ${{ needs.count-files.outputs.count }}
